name: madadgar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0" # Use Dart SDK 3.3.x (latest stable)

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  timeago: ^3.3.0
  image_picker: ^0.8.4+6
  permission_handler: ^11.0.1
  google_fonts: ^5.0.0
  http: ^1.4.0
  path: ^1.8.3
  flutter_animate: ^4.1.1
  flutter_svg: ^2.0.7


  # Firebase core and services
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.17.4
  firebase_auth_web: ^5.8.10
  firebase_analytics: ^10.10.4
  firebase_messaging: ^14.7.16
  firebase_messaging_web: ^3.5.17
  firebase_storage: ^11.6.5
  firebase_storage_web: ^3.7.0

  # Utility packages
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  cloudinary_public: ^0.23.1
  dio: ^5.8.0+1
  http_parser: ^4.1.2
  mime: ^1.0.6
  file_picker: ^8.0.7
  open_file: ^3.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
