// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:543085921164:web:a229a29630f07981bc8ca9',
    messagingSenderId: '543085921164',
    projectId: '***REMOVED***-f2760',
    authDomain: '***REMOVED***-f2760.firebaseapp.com',
    storageBucket: '***REMOVED***-f2760.firebasestorage.app',
    measurementId: 'G-R4PCRKGL4P',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:543085921164:android:fc7f037c90aea586bc8ca9',
    messagingSenderId: '543085921164',
    projectId: '***REMOVED***-f2760',
    storageBucket: '***REMOVED***-f2760.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:543085921164:ios:d367fa9e23b1da61bc8ca9',
    messagingSenderId: '543085921164',
    projectId: '***REMOVED***-f2760',
    storageBucket: '***REMOVED***-f2760.firebasestorage.app',
    iosBundleId: 'com.example.***REMOVED***',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
    appId: '1:543085921164:ios:d367fa9e23b1da61bc8ca9',
    messagingSenderId: '543085921164',
    projectId: '***REMOVED***-f2760',
    storageBucket: '***REMOVED***-f2760.firebasestorage.app',
    iosBundleId: 'com.example.***REMOVED***',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:543085921164:web:22b0457eee0397c5bc8ca9',
    messagingSenderId: '543085921164',
    projectId: '***REMOVED***-f2760',
    authDomain: '***REMOVED***-f2760.firebaseapp.com',
    storageBucket: '***REMOVED***-f2760.firebasestorage.app',
    measurementId: 'G-17X5KBMP0Q',
  );
}
