// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ_tWu5dO-AWg-iDiow9awXwgIiDUbL-k',
    appId: '1:543085921164:web:a229a29630f07981bc8ca9',
    messagingSenderId: '543085921164',
    projectId: 'madadgar-f2760',
    authDomain: 'madadgar-f2760.firebaseapp.com',
    storageBucket: 'madadgar-f2760.firebasestorage.app',
    measurementId: 'G-R4PCRKGL4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXnN5-6mTa8NGx-zunazgcfwX-UmN6yCc',
    appId: '1:543085921164:android:fc7f037c90aea586bc8ca9',
    messagingSenderId: '543085921164',
    projectId: 'madadgar-f2760',
    storageBucket: 'madadgar-f2760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsjFMFJQcFEK7kGloeNF1nKUU2j5YRIPE',
    appId: '1:543085921164:ios:d367fa9e23b1da61bc8ca9',
    messagingSenderId: '543085921164',
    projectId: 'madadgar-f2760',
    storageBucket: 'madadgar-f2760.firebasestorage.app',
    iosBundleId: 'com.example.madadgar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsjFMFJQcFEK7kGloeNF1nKUU2j5YRIPE',
    appId: '1:543085921164:ios:d367fa9e23b1da61bc8ca9',
    messagingSenderId: '543085921164',
    projectId: 'madadgar-f2760',
    storageBucket: 'madadgar-f2760.firebasestorage.app',
    iosBundleId: 'com.example.madadgar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ_tWu5dO-AWg-iDiow9awXwgIiDUbL-k',
    appId: '1:543085921164:web:22b0457eee0397c5bc8ca9',
    messagingSenderId: '543085921164',
    projectId: 'madadgar-f2760',
    authDomain: 'madadgar-f2760.firebaseapp.com',
    storageBucket: 'madadgar-f2760.firebasestorage.app',
    measurementId: 'G-17X5KBMP0Q',
  );
}
