import 'dart:io';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:madadgar/config/theme.dart';
import 'package:madadgar/models/verification_request.dart';
import 'package:madadgar/services/verification_service.dart';

class VerificationSummaryScreen extends StatefulWidget {
  final File cnicImageFile;
  final File faceImageFile;
  final String cnicNumber;
  final String dateOfBirth;

  const VerificationSummaryScreen({
    super.key,
    required this.cnicImageFile,
    required this.faceImageFile,
    required this.cnicNumber,
    required this.dateOfBirth,
  });

  @override
  State<VerificationSummaryScreen> createState() => _VerificationSummaryScreenState();
}

class _VerificationSummaryScreenState extends State<VerificationSummaryScreen> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _cnicController;
  late TextEditingController _dobController;
  late TextEditingController _nameController;

  bool _isSubmitting = false;
  final VerificationService _verificationService = VerificationService();

  @override
  void initState() {
    super.initState();
    _cnicController = TextEditingController(text: widget.cnicNumber);
    _dobController = TextEditingController(text: widget.dateOfBirth);
    _nameController = TextEditingController(); // We didn't auto-extract this reliably
  }

  @override
  void dispose() {
    _cnicController.dispose();
    _dobController.dispose();
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to verify.')),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final request = VerificationRequestModel(
        id: '', // Generated by service
        userId: user.uid,
        cnicNumber: _cnicController.text.trim(),
        dateOfBirth: _dobController.text.trim(),
        fullName: _nameController.text.trim(),
        submittedAt: DateTime.now(),
      );

      await _verificationService.submitLiveVerificationRequest(
        request: request,
        cnicImageFile: widget.cnicImageFile,
        faceImageFile: widget.faceImageFile,
      );

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Verification submitted! An admin will review it shortly.')),
      );
      
      // Pop back to the profile screen
      Navigator.of(context).popUntil((route) => route.isFirst);

    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Confirm Details', style: TextStyle(color: Colors.white)),
        backgroundColor: MadadgarTheme.primaryColor,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: _isSubmitting
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const Text(
                      'Review Captured Images',
                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            children: [
                              const Text('CNIC'),
                              const SizedBox(height: 8),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: Image.file(widget.cnicImageFile, height: 100, fit: BoxFit.cover),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            children: [
                              const Text('Live Face'),
                              const SizedBox(height: 8),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: Image.file(widget.faceImageFile, height: 100, fit: BoxFit.cover),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 32),
                    const Text(
                      'Verify Extracted Data',
                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Please correct any mistakes made by the automatic scanner.',
                      style: TextStyle(color: Colors.grey),
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _cnicController,
                      decoration: const InputDecoration(
                        labelText: 'CNIC Number',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _nameController,
                      decoration: const InputDecoration(
                        labelText: 'Full Name',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _dobController,
                      decoration: const InputDecoration(
                        labelText: 'Date of Birth',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 32),
                    ElevatedButton(
                      onPressed: _submit,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: MadadgarTheme.primaryColor,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: const Text(
                        'Submit for Verification',
                        style: TextStyle(fontSize: 16, color: Colors.white),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
